name: Nu-Tongues Binary Generation

on:
  workflow_dispatch

jobs:
  build_amd64:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3.1.0

    - name: Install needed packages
      run: sudo apt-get update && sudo apt-get install rustc cargo -y

    - name: Build
      run: cargo build --target=x86_64-unknown-linux-gnu

    - name: Prep for upload
      run: mkdir -p builds/amd64 && cp target/x86_64-unknown-linux-gnu/debug/nu_plugin_nu-tongues builds/amd64

    - uses: actions/upload-artifact@v3.1.2
      with:
        name: nu-tongues (AMD64)
        path: builds/amd64
        
  build_arm64:
    runs-on: ubuntu-24.04-arm
    steps:
    - uses: actions/checkout@v3.1.0

    - name: Install needed packages
      run: sudo apt-get update && sudo apt-get install rustc cargo -y

    - name: Build
      run: cargo build --target=aarch64-unknown-linux-gnu

    - name: Prep for upload
      run: mkdir -p builds/arm64 && cp target/aarch64-unknown-linux-gnu/debug/nu_plugin_nu-tongues builds/arm64

    - uses: actions/upload-artifact@v3.1.2
      with:
        name: nu-tongues (ARM64)
        path: builds/arm64

